  main = ".open-next/worker.js"
  name = "cleaner-rooster-nextjs-prod"
  compatibility_date = "2025-03-25"
  compatibility_flags = ["nodejs_compat"]
  [assets]
  directory = ".open-next/assets"
  binding = "ASSETS"

[[r2_buckets]]
  binding = "NEXT_INC_CACHE_R2_BUCKET"
  bucket_name = "cleaner-rooster-next"